export const EVENT_LOADED = 'EVENT_LOADED';
export const ASIDE_LOADED = 'ASIDE_LOADED';
export const SHOW_BAR = 'SHOW_BAR';
export const LOADING_INDICATOR = 'LOADING_INDICATOR';
export const LOADING_INDICATOR_LOGIN = 'LOADING_INDICATOR_LOGIN';
export const EVENTS_ERROR = 'EVENTS_ERROR';
export const SET_EVENTS_PAGE = 'SET_EVENTS_PAGE';
export const EVENT_PAGE_LOADED = 'EVENT_PAGE_LOADED';
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const RESET_LOGIN_ERROR = 'RESET_LOGIN_ERROR';
export const RESET_USER_DATA = 'RESET_USER_DATA';
export const PRICE_RANGES = 'PRICE_RANGES';
export const PRICE_INDICATOR = 'PRICE_INDICATOR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVED_FROM_CART = 'REMOVED_FROM_CART';



